version: "3.9"
services:
  api:
    build: ./api
    container_name: calculator-api
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./api:/calculator
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
    network_mode: host

  telegrambot:
    build: ./telegrambot
    container_name: calculator-telegrambot
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - api
    volumes:
      - ./telegrambot:/telegrambot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CALCULATOR_URL: http://localhost:8000
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_ECHO: false

    network_mode: host

  nginx:
    image: nginx:alpine
    container_name: calculator-nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: calculator-postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: calculator-redis
    network_mode: host
    restart: unless-stopped
    command: ["redis-server"]

volumes:
  db: null
