version: "3.9"
services:
  api:
    build: ./api
    container_name: calculator-api
    restart: unless-stopped
    network_mode: host

  telegrambot:
    build: ./telegrambot
    container_name: calculator-telegrambot
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      CALCULATOR_URL: http://localhost:8000
    network_mode: host

  nginx:
    image: nginx:alpine
    container_name: calculator-nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  postgres:
    image: postgres:alpine
    container_name: calculator-postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: calculator-redis
    network_mode: host
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  db: null
